### ISSUE TITLE
[Fix]  페이지별 수정사항

### ISSUE THREAD

**Issue by pearpearB** [42organization/42arcade.gg.client#336]
### ISSUE
 * Type: `fix`
 * Detail: 페이지별 수정사항
 
 ### TODO
- 레이아웃
  - [ ] 알림 내용 길어지면 깨지는 현상 수정하기
- 랭크 페이지
  - [x] 게임을 한번도 하지 않은 경우(랭킹 -1) 점수 보여주지 않기
  - [x] 점수가 잘 안보이므로 승률 제거하고 맨 오른쪽 자리에 점수 보여주기
  - [x] 함수 이름 onClick 수정하기
- 게임 페이지
  - [ ]  ~~이미 받아온 이미지는 S3에 받아놓고 보여줘서 이미지 로딩 속도 줄이기~~
- 유저 페이지
  - [ ] ~~아무것도 없을 때  placeholder 추가하기(현재 pending인지 null인지 알 수 없다)~~
  - [x] 승패 수 추가하기

**Comment by Arkingco** [comment]
s3에 받아서 이미지 처리하는건 어려운 작업이 될 것 같아서 급한 업데이트 미리 하고 진행하는걸로 자배님과 합의 하였습니다!!
