### ISSUE TITLE
[Fix]  메뉴바&알림바 열었을 때, 백드롭 화면 스크롤 되는 문제

### ISSUE THREAD

**Issue by pearpearB** [42organization/42arcade.gg.client#492]
### ISSUE
 * Type: `fix`
 * Detail: 메뉴바&알림바 열었을 때, 백드롭 화면 스크롤 되는 문제
 
 ### TODO
- [ ]  메뉴바&알림바 열었을 때, 백드롭 화면 스크롤 되는 문제

**Comment by HyeongwooIM** [comment]
해결완료
